ci(workflows): splited logic of deploy branch pr in 2 workflows for update deployment status in pr

diff --git a/.github/workflows/deploy-ephemeral-env-aws.yaml b/.github/workflows/deploy-ephemeral-env-aws.yaml
--- a/.github/workflows/deploy-ephemeral-env-aws.yaml
+++ b/.github/workflows/deploy-ephemeral-env-aws.yaml
@@ -1,34 +1,47 @@
-name: Deploy PR Branch
+name: Deploy to Ephemeral AWS Environments
 
-run-name: "Deploy PR #${{ github.event.issue.number }} by @${{ github.event.comment.user.login }}"
+run-name: "Deploy to ${{ inputs.github-env }} | ${{ github.actor }}"
 on:
-  issue_comment:
-    types: [created]
+  workflow_dispatch:
+    inputs:
+      aws-env:
+        description: "AWS Elastic Beanstalk Environment Name"
+        required: true
+        default: "app-staging"
+        type: string
+
+      github-env:
+        description: "GitHub Deployment Environment"
+        required: true
+        default: "staging"
+        type: string
+
+      report-pr:
+        description: "PR to add report comments to"
+        type: number
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.aws-env }}-${{ inputs.github-env }}
+  cancel-in-progress: true
 
 jobs:
-  trigger-pr-branch-deploy:
+  deploy:
     runs-on: ubuntu-latest
     permissions:
-      actions: write
       pull-requests: write
     environment:
-      name: "staging"
+      name: ${{ inputs.github-env }}
       url: "http://${{ steps.get-aws-env-cname.outputs.AWS_ENV_CNAME }}"
-    if: github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.body == '/deploy'
     steps:
-      - name: Get Pull Request Head Ref
-        id: get-head-ref
-        uses: actions/github-script@v8
-        with:
-          result-encoding: string
-          script: |
-            const response = await github.rest.pulls.get({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                pull_number: context.issue.number
-            });
-            console.log(response.data)
-            return response.data.head.ref
+      - name: Debug Info
+        run: |
+          echo "::notice::Deploying to AWS env: ${{ inputs.aws-env }} | GitHub env: ${{ inputs.github-env }} | PR: ${{ inputs.report-pr }} | Branch: ${{ github.ref_name }} | SHA: ${{ github.sha }} "
+
+      - name: Avoid deploying to production using a non production env
+        if: inputs.aws-env == vars.AWS_EB_PRODUCTION_ENV && inputs.github-env != 'production'
+        run: |
+          echo "::error::Cannot deploy to production using a non prodcuction environment"
+          exit 1
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v6
@@ -38,7 +51,8 @@ jobs:
           aws-region: ${{ vars.AWS_REGION }}
 
       - name: Update Pull Request (Start)
-        uses: actions/github-script@v6
+        uses: actions/github-script@v8
+        if: inputs.report-pr
         continue-on-error: true
         with:
           script: |
@@ -50,14 +64,12 @@ jobs:
             github.rest.issues.createComment({
               owner: context.repo.owner,
               repo: context.repo.repo,
-              issue_number: context.issue.number,
+              issue_number: ${{ inputs.report-pr }},
               body: comment
             })
 
       - name: Checkout Reposiotry Code
         uses: actions/checkout@v6
-        with:
-          ref: ${{ steps.get-head-ref.outputs.result }}
 
       - name: Setup Node Environment
         uses: actions/setup-node@v6
@@ -69,7 +81,7 @@ jobs:
         run: npm ci
 
       - name: Build App
-        run: npm  run build
+        run: npm run build
         env:
           FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
 
@@ -87,7 +99,7 @@ jobs:
         run: |
           echo "AWS_ENV_NAME=$(aws elasticbeanstalk describe-environments \
             --application-name ${{ vars.AWS_EB_APP_NAME }} \
-            --environment-names app-PR-${{ github.event.issue.number }} \
+            --environment-names ${{ inputs.aws-env }} \
             --query "Environments[0].EnvironmentName" \
             --output text)" >> $GITHUB_OUTPUT
 
@@ -96,7 +108,7 @@ jobs:
         run: |
           echo "AWS_ENV_STATUS=$(aws elasticbeanstalk describe-environments \
             --application-name ${{ vars.AWS_EB_APP_NAME }} \
-            --environment-names app-PR-${{ github.event.issue.number }} \
+            --environment-names ${{ inputs.aws-env }} \
             --query "Environments[0].Status" \
             --output text)" >> $GITHUB_OUTPUT
 
@@ -109,23 +121,23 @@ jobs:
       - name: Create a New Environment
         if: steps.get-aws-env-name.outputs.AWS_ENV_NAME == 'None' || steps.get-aws-env-status.outputs.AWS_ENV_STATUS == 'Terminated'
         run: |
-          eb create app-PR-${{ github.event.issue.number }} \
+          eb create ${{ inputs.aws-env }} \
           --instance-type ${{ vars.AWS_EB_ENV_INSTANCE_TYPE }} \
           --single \
-          --cname app-PR-${{ github.event.issue.number }} \
+          --cname ${{ inputs.aws-env }} \
           --envvars FLAGSMITH_KEY=${{ secrets.FLAGSMITH_KEY }} \
           --region ${{ vars.AWS_REGION }}
 
       - name: Deploy if Environment Exists
-        if: steps.get-aws-env-name.outputs.AWS_ENV_NAME == format('app-PR-{0}', github.event.issue.number) && steps.get-aws-env-status.outputs.AWS_ENV_STATUS != 'Terminated'
-        run: eb deploy app-PR-${{ github.event.issue.number }}
+        if: steps.get-aws-env-name.outputs.AWS_ENV_NAME == inputs.aws-env && steps.get-aws-env-status.outputs.AWS_ENV_STATUS != 'Terminated'
+        run: eb deploy ${{ inputs.aws-env }}
 
       - name: Get AWS ENV CNAME
         id: get-aws-env-cname
         run: |
           echo "AWS_ENV_CNAME=$(aws elasticbeanstalk describe-environments \
             --application-name ${{ vars.AWS_EB_APP_NAME }} \
-            --environment-names app-PR-${{ github.event.issue.number }} \
+            --environment-names ${{ inputs.aws-env }} \
             --query "Environments[0].CNAME" \
             --output text)" >> $GITHUB_OUTPUT
 
@@ -142,14 +154,15 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "🚀 Deployment to AWS environment *app-PR-${{ github.event.issue.number }}* using *staging* GitHub wnvironment  was successfull. <http://${{ steps.get-aws-env-cname.outputs.AWS_ENV_CNAME }}|View Deployment>"
+                    "text": "🚀 Deployment to AWS environment *${{ inputs.aws-env }}* using *staging* GitHub wnvironment  was successfull. <http://${{ steps.get-aws-env-cname.outputs.AWS_ENV_CNAME }}|View Deployment>"
                   }
                 }
               ] 
             }
+
       - name: Update Pull Request (Success)
         uses: actions/github-script@v8
-        if: success()
+        if: success() && inputs.report-pr
         continue-on-error: true
         with:
           script: |
@@ -160,7 +173,7 @@ jobs:
             github.rest.issues.createComment({
               owner: context.repo.owner,
               repo: context.repo.repo,
-              issue_number: ${{ github.event.issue.number }},
+              issue_number: ${{ inputs.report-pr }},
               body: comment
             })
 
@@ -177,9 +190,10 @@ jobs:
             github.rest.issues.createComment({
               owner: context.repo.owner,
               repo: context.repo.repo,
-              issue_number: ${{ github.event.issue.number }},
+              issue_number: ${{ inputs.report-pr }},
               body: comment
             })
+
       - name: Abort if Cancelled
         if: cancelled() && steps.install-eb-cli.conclusion == 'success'
-        run: eb abort app-PR-${{ github.event.issue.number }}
+        run: eb abort app-PR-${{ inputs.report-pr }}
